services:
  - type: web
    name: supercanal
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    healthCheckPath: /login.html
    nodeVersion: 18.17.0
