services:
  - type: web
    name: supercanal
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: API_USERNAME
        value: supercanal
      - key: API_PASSWORD
        sync: false
    healthCheckPath: /login.html
    nodeVersion: 18.17.0
